/**
 * Institutional Feeder Schools Directory
 * Pre-seeded schools covering primary catchment areas in Tamil Nadu
 * (Namakkal, Erode, Salem, Coimbatore, Tirupur, Karur, Dharmapuri, Krishnagiri, etc.)
 */

export interface SeedSchool {
  schoolName: string;
  city: string;
  district: string;
  state: string;
  schoolType: string;
  schoolCode?: string;
  pincode?: string;
  displayName: string;
  isActive: boolean;
}

export const FEEDER_SCHOOLS: SeedSchool[] = [
  // ─── Namakkal District (Primary Institutional Zone) ─────────
  {
    schoolName: 'Government Boys Higher Secondary School, Tiruchengode',
    city: 'Tiruchengode',
    district: 'Namakkal',
    state: 'Tamil Nadu',
    schoolType: 'Government',
    displayName: 'Government Boys Higher Secondary School — Tiruchengode, Namakkal',
    isActive: true,
  },
  {
    schoolName: 'Government Girls Higher Secondary School, Tiruchengode',
    city: 'Tiruchengode',
    district: 'Namakkal',
    state: 'Tamil Nadu',
    schoolType: 'Government',
    displayName: 'Government Girls Higher Secondary School — Tiruchengode, Namakkal',
    isActive: true,
  },
  {
    schoolName: 'K.S.R. Matriculation Higher Secondary School, Tiruchengode',
    city: 'Tiruchengode',
    district: 'Namakkal',
    state: 'Tamil Nadu',
    schoolType: 'Matriculation',
    displayName: 'K.S.R. Matriculation Higher Secondary School — Tiruchengode, Namakkal',
    isActive: true,
  },
  {
    schoolName: 'K.S.R. Akshara Academy (CBSE), Tiruchengode',
    city: 'Tiruchengode',
    district: 'Namakkal',
    state: 'Tamil Nadu',
    schoolType: 'CBSE',
    displayName: 'K.S.R. Akshara Academy (CBSE) — Tiruchengode, Namakkal',
    isActive: true,
  },
  {
    schoolName: 'Sengunthar Higher Secondary School, Tiruchengode',
    city: 'Tiruchengode',
    district: 'Namakkal',
    state: 'Tamil Nadu',
    schoolType: 'Government Aided',
    displayName: 'Sengunthar Higher Secondary School — Tiruchengode, Namakkal',
    isActive: true,
  },
  {
    schoolName: 'Vivekananda Girls Higher Secondary School, Tiruchengode',
    city: 'Tiruchengode',
    district: 'Namakkal',
    state: 'Tamil Nadu',
    schoolType: 'Private Aided',
    displayName: 'Vivekananda Girls Higher Secondary School — Tiruchengode, Namakkal',
    isActive: true,
  },
  {
    schoolName: 'Government Higher Secondary School, Namakkal',
    city: 'Namakkal',
    district: 'Namakkal',
    state: 'Tamil Nadu',
    schoolType: 'Government',
    displayName: 'Government Higher Secondary School — Namakkal, Namakkal',
    isActive: true,
  },
  {
    schoolName: 'Government Girls Higher Secondary School, Namakkal',
    city: 'Namakkal',
    district: 'Namakkal',
    state: 'Tamil Nadu',
    schoolType: 'Government',
    displayName: 'Government Girls Higher Secondary School — Namakkal, Namakkal',
    isActive: true,
  },
  {
    schoolName: 'Government Higher Secondary School, Paramathi Velur',
    city: 'Paramathi Velur',
    district: 'Namakkal',
    state: 'Tamil Nadu',
    schoolType: 'Government',
    displayName: 'Government Higher Secondary School — Paramathi Velur, Namakkal',
    isActive: true,
  },
  {
    schoolName: 'Government Higher Secondary School, Rasipuram',
    city: 'Rasipuram',
    district: 'Namakkal',
    state: 'Tamil Nadu',
    schoolType: 'Government',
    displayName: 'Government Higher Secondary School — Rasipuram, Namakkal',
    isActive: true,
  },
  {
    schoolName: 'Government Higher Secondary School, Pallipalayam',
    city: 'Pallipalayam',
    district: 'Namakkal',
    state: 'Tamil Nadu',
    schoolType: 'Government',
    displayName: 'Government Higher Secondary School — Pallipalayam, Namakkal',
    isActive: true,
  },
  {
    schoolName: 'Government Higher Secondary School, Komarapalayam',
    city: 'Komarapalayam',
    district: 'Namakkal',
    state: 'Tamil Nadu',
    schoolType: 'Government',
    displayName: 'Government Higher Secondary School — Komarapalayam, Namakkal',
    isActive: true,
  },
  {
    schoolName: 'Green Park Higher Secondary School, Namakkal',
    city: 'Namakkal',
    district: 'Namakkal',
    state: 'Tamil Nadu',
    schoolType: 'Matriculation',
    displayName: 'Green Park Higher Secondary School — Namakkal, Namakkal',
    isActive: true,
  },
  {
    schoolName: 'Kurinji Higher Secondary School, Namakkal',
    city: 'Namakkal',
    district: 'Namakkal',
    state: 'Tamil Nadu',
    schoolType: 'Matriculation',
    displayName: 'Kurinji Higher Secondary School — Namakkal, Namakkal',
    isActive: true,
  },
  {
    schoolName: 'Selvam Higher Secondary School, Namakkal',
    city: 'Namakkal',
    district: 'Namakkal',
    state: 'Tamil Nadu',
    schoolType: 'Matriculation',
    displayName: 'Selvam Higher Secondary School — Namakkal, Namakkal',
    isActive: true,
  },
  {
    schoolName: 'Bharathi Higher Secondary School, Reddipatti, Namakkal',
    city: 'Namakkal',
    district: 'Namakkal',
    state: 'Tamil Nadu',
    schoolType: 'Matriculation',
    displayName: 'Bharathi Higher Secondary School — Reddipatti, Namakkal',
    isActive: true,
  },
  {
    schoolName: 'Spectrum Higher Secondary School, Namakkal',
    city: 'Namakkal',
    district: 'Namakkal',
    state: 'Tamil Nadu',
    schoolType: 'Matriculation',
    displayName: 'Spectrum Higher Secondary School — Namakkal, Namakkal',
    isActive: true,
  },
  {
    schoolName: 'Sri Vidya Mandir Higher Secondary School, Rasipuram',
    city: 'Rasipuram',
    district: 'Namakkal',
    state: 'Tamil Nadu',
    schoolType: 'Matriculation',
    displayName: 'Sri Vidya Mandir Higher Secondary School — Rasipuram, Namakkal',
    isActive: true,
  },
  {
    schoolName: 'SPK Higher Secondary School, Namakkal',
    city: 'Namakkal',
    district: 'Namakkal',
    state: 'Tamil Nadu',
    schoolType: 'Matriculation',
    displayName: 'SPK Higher Secondary School — Namakkal, Namakkal',
    isActive: true,
  },
  {
    schoolName: 'Jayarani Matriculation HSS, Tiruchengode',
    city: 'Tiruchengode',
    district: 'Namakkal',
    state: 'Tamil Nadu',
    schoolType: 'Matriculation',
    displayName: 'Jayarani Matriculation HSS — Tiruchengode, Namakkal',
    isActive: true,
  },

  // ─── Erode District ──────────────────────────────────────────
  {
    schoolName: 'Government Model Higher Secondary School, Erode',
    city: 'Erode',
    district: 'Erode',
    state: 'Tamil Nadu',
    schoolType: 'Government',
    displayName: 'Government Model Higher Secondary School — Erode, Erode',
    isActive: true,
  },
  {
    schoolName: 'Government Girls Higher Secondary School, Erode',
    city: 'Erode',
    district: 'Erode',
    state: 'Tamil Nadu',
    schoolType: 'Government',
    displayName: 'Government Girls Higher Secondary School — Erode, Erode',
    isActive: true,
  },
  {
    schoolName: 'Sengunthar Higher Secondary School, Erode',
    city: 'Erode',
    district: 'Erode',
    state: 'Tamil Nadu',
    schoolType: 'Government Aided',
    displayName: 'Sengunthar Higher Secondary School — Erode, Erode',
    isActive: true,
  },
  {
    schoolName: 'Railway Colony Higher Secondary School, Erode',
    city: 'Erode',
    district: 'Erode',
    state: 'Tamil Nadu',
    schoolType: 'Government Aided',
    displayName: 'Railway Colony Higher Secondary School — Erode, Erode',
    isActive: true,
  },
  {
    schoolName: 'Kalaimagal Kalvi Nilayam Girls HSS, Erode',
    city: 'Erode',
    district: 'Erode',
    state: 'Tamil Nadu',
    schoolType: 'Government Aided',
    displayName: 'Kalaimagal Kalvi Nilayam Girls HSS — Erode, Erode',
    isActive: true,
  },
  {
    schoolName: 'Carmel Higher Secondary School, Erode',
    city: 'Erode',
    district: 'Erode',
    state: 'Tamil Nadu',
    schoolType: 'Government Aided',
    displayName: 'Carmel Higher Secondary School — Erode, Erode',
    isActive: true,
  },
  {
    schoolName: 'Government Boys Higher Secondary School, Bhavani',
    city: 'Bhavani',
    district: 'Erode',
    state: 'Tamil Nadu',
    schoolType: 'Government',
    displayName: 'Government Boys Higher Secondary School — Bhavani, Erode',
    isActive: true,
  },
  {
    schoolName: 'Government Girls Higher Secondary School, Bhavani',
    city: 'Bhavani',
    district: 'Erode',
    state: 'Tamil Nadu',
    schoolType: 'Government',
    displayName: 'Government Girls Higher Secondary School — Bhavani, Erode',
    isActive: true,
  },
  {
    schoolName: 'Diamond Jubilee Higher Secondary School, Gobichettipalayam',
    city: 'Gobichettipalayam',
    district: 'Erode',
    state: 'Tamil Nadu',
    schoolType: 'Government Aided',
    displayName: 'Diamond Jubilee Higher Secondary School — Gobichettipalayam, Erode',
    isActive: true,
  },
  {
    schoolName: 'Government Higher Secondary School, Gobichettipalayam',
    city: 'Gobichettipalayam',
    district: 'Erode',
    state: 'Tamil Nadu',
    schoolType: 'Government',
    displayName: 'Government Higher Secondary School — Gobichettipalayam, Erode',
    isActive: true,
  },
  {
    schoolName: 'Kongu Vellalar Matriculation HSS, Perundurai',
    city: 'Perundurai',
    district: 'Erode',
    state: 'Tamil Nadu',
    schoolType: 'Matriculation',
    displayName: 'Kongu Vellalar Matriculation HSS — Perundurai, Erode',
    isActive: true,
  },
  {
    schoolName: 'Government Higher Secondary School, Perundurai',
    city: 'Perundurai',
    district: 'Erode',
    state: 'Tamil Nadu',
    schoolType: 'Government',
    displayName: 'Government Higher Secondary School — Perundurai, Erode',
    isActive: true,
  },
  {
    schoolName: 'Balaranga Higher Secondary School, Erode',
    city: 'Erode',
    district: 'Erode',
    state: 'Tamil Nadu',
    schoolType: 'Matriculation',
    displayName: 'Balaranga Higher Secondary School — Erode, Erode',
    isActive: true,
  },
  {
    schoolName: 'The Indian Public School (TIPS), Erode',
    city: 'Erode',
    district: 'Erode',
    state: 'Tamil Nadu',
    schoolType: 'CBSE',
    displayName: 'The Indian Public School (TIPS) — Erode, Erode',
    isActive: true,
  },

  // ─── Salem District ──────────────────────────────────────────
  {
    schoolName: 'Government Model Higher Secondary School, Salem',
    city: 'Salem',
    district: 'Salem',
    state: 'Tamil Nadu',
    schoolType: 'Government',
    displayName: 'Government Model Higher Secondary School — Salem, Salem',
    isActive: true,
  },
  {
    schoolName: 'Government Girls Higher Secondary School, Salem',
    city: 'Salem',
    district: 'Salem',
    state: 'Tamil Nadu',
    schoolType: 'Government',
    displayName: 'Government Girls Higher Secondary School — Salem, Salem',
    isActive: true,
  },
  {
    schoolName: 'Gokulnatha Hindu Mahajana Higher Secondary School, Salem',
    city: 'Salem',
    district: 'Salem',
    state: 'Tamil Nadu',
    schoolType: 'Government Aided',
    displayName: 'Gokulnatha Hindu Mahajana Higher Secondary School — Salem, Salem',
    isActive: true,
  },
  {
    schoolName: 'Sri Sarada Vidyalaya Girls Higher Secondary School, Salem',
    city: 'Salem',
    district: 'Salem',
    state: 'Tamil Nadu',
    schoolType: 'Government Aided',
    displayName: 'Sri Sarada Vidyalaya Girls Higher Secondary School — Salem, Salem',
    isActive: true,
  },
  {
    schoolName: 'St. Paul\'s Higher Secondary School, Salem',
    city: 'Salem',
    district: 'Salem',
    state: 'Tamil Nadu',
    schoolType: 'Government Aided',
    displayName: 'St. Paul\'s Higher Secondary School — Salem, Salem',
    isActive: true,
  },
  {
    schoolName: 'Little Flower Higher Secondary School, Salem',
    city: 'Salem',
    district: 'Salem',
    state: 'Tamil Nadu',
    schoolType: 'Government Aided',
    displayName: 'Little Flower Higher Secondary School — Salem, Salem',
    isActive: true,
  },
  {
    schoolName: 'Holy Cross Higher Secondary School, Salem',
    city: 'Salem',
    district: 'Salem',
    state: 'Tamil Nadu',
    schoolType: 'Government Aided',
    displayName: 'Holy Cross Higher Secondary School — Salem, Salem',
    isActive: true,
  },
  {
    schoolName: 'Government Boys Higher Secondary School, Sankari',
    city: 'Sankari',
    district: 'Salem',
    state: 'Tamil Nadu',
    schoolType: 'Government',
    displayName: 'Government Boys Higher Secondary School — Sankari, Salem',
    isActive: true,
  },
  {
    schoolName: 'Government Girls Higher Secondary School, Sankari',
    city: 'Sankari',
    district: 'Salem',
    state: 'Tamil Nadu',
    schoolType: 'Government',
    displayName: 'Government Girls Higher Secondary School — Sankari, Salem',
    isActive: true,
  },
  {
    schoolName: 'Government Higher Secondary School, Attur',
    city: 'Attur',
    district: 'Salem',
    state: 'Tamil Nadu',
    schoolType: 'Government',
    displayName: 'Government Higher Secondary School — Attur, Salem',
    isActive: true,
  },
  {
    schoolName: 'Government Boys Higher Secondary School, Mettur Dam',
    city: 'Mettur',
    district: 'Salem',
    state: 'Tamil Nadu',
    schoolType: 'Government',
    displayName: 'Government Boys Higher Secondary School — Mettur, Salem',
    isActive: true,
  },
  {
    schoolName: 'Golden Gates Matriculation HSS, Salem',
    city: 'Salem',
    district: 'Salem',
    state: 'Tamil Nadu',
    schoolType: 'Matriculation',
    displayName: 'Golden Gates Matriculation HSS — Salem, Salem',
    isActive: true,
  },
  {
    schoolName: 'Cluny Higher Secondary School, Salem',
    city: 'Salem',
    district: 'Salem',
    state: 'Tamil Nadu',
    schoolType: 'Matriculation',
    displayName: 'Cluny Higher Secondary School — Salem, Salem',
    isActive: true,
  },
  {
    schoolName: 'Kendriya Vidyalaya, Salem',
    city: 'Salem',
    district: 'Salem',
    state: 'Tamil Nadu',
    schoolType: 'CBSE',
    displayName: 'Kendriya Vidyalaya — Salem, Salem',
    isActive: true,
  },

  // ─── Coimbatore District ─────────────────────────────────────
  {
    schoolName: 'Stanes Higher Secondary School, Coimbatore',
    city: 'Coimbatore',
    district: 'Coimbatore',
    state: 'Tamil Nadu',
    schoolType: 'Government Aided',
    displayName: 'Stanes Higher Secondary School — Coimbatore, Coimbatore',
    isActive: true,
  },
  {
    schoolName: 'St. Michael\'s Higher Secondary School, Coimbatore',
    city: 'Coimbatore',
    district: 'Coimbatore',
    state: 'Tamil Nadu',
    schoolType: 'Government Aided',
    displayName: 'St. Michael\'s Higher Secondary School — Coimbatore, Coimbatore',
    isActive: true,
  },
  {
    schoolName: 'PSG Sarvajana Higher Secondary School, Peelamedu, Coimbatore',
    city: 'Coimbatore',
    district: 'Coimbatore',
    state: 'Tamil Nadu',
    schoolType: 'Government Aided',
    displayName: 'PSG Sarvajana Higher Secondary School — Peelamedu, Coimbatore',
    isActive: true,
  },
  {
    schoolName: 'Suburban Higher Secondary School, Ramnagar, Coimbatore',
    city: 'Coimbatore',
    district: 'Coimbatore',
    state: 'Tamil Nadu',
    schoolType: 'Government Aided',
    displayName: 'Suburban Higher Secondary School — Ramnagar, Coimbatore',
    isActive: true,
  },
  {
    schoolName: 'Mani Higher Secondary School, Coimbatore',
    city: 'Coimbatore',
    district: 'Coimbatore',
    state: 'Tamil Nadu',
    schoolType: 'Government Aided',
    displayName: 'Mani Higher Secondary School — Coimbatore, Coimbatore',
    isActive: true,
  },
  {
    schoolName: 'Government Higher Secondary School, Coimbatore',
    city: 'Coimbatore',
    district: 'Coimbatore',
    state: 'Tamil Nadu',
    schoolType: 'Government',
    displayName: 'Government Higher Secondary School — Coimbatore, Coimbatore',
    isActive: true,
  },
  {
    schoolName: 'Government Higher Secondary School, Pollachi',
    city: 'Pollachi',
    district: 'Coimbatore',
    state: 'Tamil Nadu',
    schoolType: 'Government',
    displayName: 'Government Higher Secondary School — Pollachi, Coimbatore',
    isActive: true,
  },
  {
    schoolName: 'GD Matriculation Higher Secondary School, Coimbatore',
    city: 'Coimbatore',
    district: 'Coimbatore',
    state: 'Tamil Nadu',
    schoolType: 'Matriculation',
    displayName: 'GD Matriculation Higher Secondary School — Coimbatore, Coimbatore',
    isActive: true,
  },
  {
    schoolName: 'Kendriya Vidyalaya, Sulur, Coimbatore',
    city: 'Coimbatore',
    district: 'Coimbatore',
    state: 'Tamil Nadu',
    schoolType: 'CBSE',
    displayName: 'Kendriya Vidyalaya — Sulur, Coimbatore',
    isActive: true,
  },

  // ─── Tirupur District ────────────────────────────────────────
  {
    schoolName: 'KSC Government Boys Higher Secondary School, Tirupur',
    city: 'Tirupur',
    district: 'Tirupur',
    state: 'Tamil Nadu',
    schoolType: 'Government',
    displayName: 'KSC Government Boys Higher Secondary School — Tirupur, Tirupur',
    isActive: true,
  },
  {
    schoolName: 'Jaivabai Municipal Girls Higher Secondary School, Tirupur',
    city: 'Tirupur',
    district: 'Tirupur',
    state: 'Tamil Nadu',
    schoolType: 'Government',
    displayName: 'Jaivabai Municipal Girls Higher Secondary School — Tirupur, Tirupur',
    isActive: true,
  },
  {
    schoolName: 'Government Higher Secondary School, Nallur, Tirupur',
    city: 'Tirupur',
    district: 'Tirupur',
    state: 'Tamil Nadu',
    schoolType: 'Government',
    displayName: 'Government Higher Secondary School — Nallur, Tirupur',
    isActive: true,
  },
  {
    schoolName: 'Bishop Ubagaraswamy Higher Secondary School, Tirupur',
    city: 'Tirupur',
    district: 'Tirupur',
    state: 'Tamil Nadu',
    schoolType: 'Government Aided',
    displayName: 'Bishop Ubagaraswamy Higher Secondary School — Tirupur, Tirupur',
    isActive: true,
  },
  {
    schoolName: 'Government Boys Higher Secondary School, Dharapuram',
    city: 'Dharapuram',
    district: 'Tirupur',
    state: 'Tamil Nadu',
    schoolType: 'Government',
    displayName: 'Government Boys Higher Secondary School — Dharapuram, Tirupur',
    isActive: true,
  },
  {
    schoolName: 'Government Girls Higher Secondary School, Kangeyam',
    city: 'Kangeyam',
    district: 'Tirupur',
    state: 'Tamil Nadu',
    schoolType: 'Government',
    displayName: 'Government Girls Higher Secondary School — Kangeyam, Tirupur',
    isActive: true,
  },
  {
    schoolName: 'Vikas Vidyalaya Matric HSS, Tirupur',
    city: 'Tirupur',
    district: 'Tirupur',
    state: 'Tamil Nadu',
    schoolType: 'Matriculation',
    displayName: 'Vikas Vidyalaya Matric HSS — Tirupur, Tirupur',
    isActive: true,
  },

  // ─── Karur, Dharmapuri, Krishnagiri & Others ─────────────────
  {
    schoolName: 'Government Higher Secondary School, Karur',
    city: 'Karur',
    district: 'Karur',
    state: 'Tamil Nadu',
    schoolType: 'Government',
    displayName: 'Government Higher Secondary School — Karur, Karur',
    isActive: true,
  },
  {
    schoolName: 'Municipal Higher Secondary School, Karur',
    city: 'Karur',
    district: 'Karur',
    state: 'Tamil Nadu',
    schoolType: 'Government',
    displayName: 'Municipal Higher Secondary School — Karur, Karur',
    isActive: true,
  },
  {
    schoolName: 'Cheran Matriculation Higher Secondary School, Karur',
    city: 'Karur',
    district: 'Karur',
    state: 'Tamil Nadu',
    schoolType: 'Matriculation',
    displayName: 'Cheran Matriculation Higher Secondary School — Karur, Karur',
    isActive: true,
  },
  {
    schoolName: 'Government Boys Higher Secondary School, Dharmapuri',
    city: 'Dharmapuri',
    district: 'Dharmapuri',
    state: 'Tamil Nadu',
    schoolType: 'Government',
    displayName: 'Government Boys Higher Secondary School — Dharmapuri, Dharmapuri',
    isActive: true,
  },
  {
    schoolName: 'Vijay Vidyalaya Higher Secondary School, Dharmapuri',
    city: 'Dharmapuri',
    district: 'Dharmapuri',
    state: 'Tamil Nadu',
    schoolType: 'Matriculation',
    displayName: 'Vijay Vidyalaya Higher Secondary School — Dharmapuri, Dharmapuri',
    isActive: true,
  },
  {
    schoolName: 'Government Boys Higher Secondary School, Krishnagiri',
    city: 'Krishnagiri',
    district: 'Krishnagiri',
    state: 'Tamil Nadu',
    schoolType: 'Government',
    displayName: 'Government Boys Higher Secondary School — Krishnagiri, Krishnagiri',
    isActive: true,
  },
  {
    schoolName: 'Government Girls Higher Secondary School, Hosur',
    city: 'Hosur',
    district: 'Krishnagiri',
    state: 'Tamil Nadu',
    schoolType: 'Government',
    displayName: 'Government Girls Higher Secondary School — Hosur, Krishnagiri',
    isActive: true,
  },
  {
    schoolName: 'St. Joseph\'s Higher Secondary School, Trichy',
    city: 'Trichy',
    district: 'Tiruchirappalli',
    state: 'Tamil Nadu',
    schoolType: 'Government Aided',
    displayName: 'St. Joseph\'s Higher Secondary School — Trichy, Tiruchirappalli',
    isActive: true,
  },
  {
    schoolName: 'National Higher Secondary School, Trichy',
    city: 'Trichy',
    district: 'Tiruchirappalli',
    state: 'Tamil Nadu',
    schoolType: 'Government Aided',
    displayName: 'National Higher Secondary School — Trichy, Tiruchirappalli',
    isActive: true,
  },
  {
    schoolName: 'Campion Anglo-Indian HSS, Trichy',
    city: 'Trichy',
    district: 'Tiruchirappalli',
    state: 'Tamil Nadu',
    schoolType: 'Government Aided',
    displayName: 'Campion Anglo-Indian HSS — Trichy, Tiruchirappalli',
    isActive: true,
  },
  {
    schoolName: 'TVS Higher Secondary School, Madurai',
    city: 'Madurai',
    district: 'Madurai',
    state: 'Tamil Nadu',
    schoolType: 'Government Aided',
    displayName: 'TVS Higher Secondary School — Madurai, Madurai',
    isActive: true,
  },
  {
    schoolName: 'Madras Christian College Higher Secondary School, Chennai',
    city: 'Chennai',
    district: 'Chennai',
    state: 'Tamil Nadu',
    schoolType: 'Government Aided',
    displayName: 'Madras Christian College Higher Secondary School — Chetpet, Chennai',
    isActive: true,
  },
  {
    schoolName: 'Santhome Higher Secondary School, Chennai',
    city: 'Chennai',
    district: 'Chennai',
    state: 'Tamil Nadu',
    schoolType: 'Government Aided',
    displayName: 'Santhome Higher Secondary School — Mylapore, Chennai',
    isActive: true,
  },
  {
    schoolName: 'DAV Boys Higher Secondary School, Gopalapuram, Chennai',
    city: 'Chennai',
    district: 'Chennai',
    state: 'Tamil Nadu',
    schoolType: 'CBSE',
    displayName: 'DAV Boys Higher Secondary School — Gopalapuram, Chennai',
    isActive: true,
  },
];
